name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        env:
          CC: gcc-8
        run: make

  test:

    name: Test
    needs: [build]
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        env:
          CC: gcc-8
        run: make

      - name: Run tests
        env:
          CC: gcc-8
          # LD_PRELOAD: ./libmy_malloc.so
        run: ./tests/reverse_me_to_improve_your_malloc.jpg